### ISSUE TITLE
A (-b) bug

### ISSUE THREAD

**Issue by Fallqs** [sLill/Windows-Grep#20]
I found that on my device, in the very file test.txt, whose content is "abcd\r\nabcd", the (^) does not match the start of the second line and the ($) does not match the end of the first line.

 It seems like "-b" command working (although I did not use it), so I tried adding "-b" to see what happens. On my device, "-b" prints it twice if a result doesn't appear in multiple lines.

![image](https://user-images.githubusercontent.com/73042569/111395866-cdeffa80-86f8-11eb-8389-02ba6c34d99e.png)

![image](https://user-images.githubusercontent.com/73042569/111395759-8ff2d680-86f8-11eb-8575-66f73c9f47cc.png)

**Comment by sLill** [comment]
This should be resolved now in v2.2. I appreciate the detailed bug report!

![IgnoreBreaksBug](https://user-images.githubusercontent.com/16293850/111489049-cd129500-8707-11eb-95ed-e38bfa1a500e.png)
